import { Html, Main, Head, NextScript } from 'next/document';
import Script from 'next/script';

export default function Document() {
    return (
        <Html lang='en'>
            <Head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='' />
                <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans&display=swap" rel="stylesheet" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>Icedtee</title>
                <meta name="description" content="Generated by create next app"></meta>
                
                <script async src="https://www.googletagmanager.com/gtag/js?id=G-QKLXGB0SHL%22%3E"></script>
<script>
  {`window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-QKLXGB0SHL');`}
</script>
            </Head>
            
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    )
}