import Header from '@/components/Header';
import "./globals.css";
import '../styles/global.scss';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='' />
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans&display=swap" rel="stylesheet" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Icedtee</title>
        <meta name="description" content="Generated by create next app"></meta>
      </head>
      <body className={inter.className}>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  )
}
